version: "3.9"
services:
  client:
    container_name: client
    build: ./task_2
    depends_on:
      redis:
        condition: service_healthy
    stdin_open: true
    tty: true

  worker:
    container_name: worker
    build: ./task_3
    depends_on:
      redis:
        condition: service_healthy
    stdin_open: true
    tty: true

  redis:
    container_name: my_redis
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
